# Generated by Django 4.1.1 on 2022-10-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('qtdparcelas', models.IntegerField(verbose_name='Quant.parcelas')),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Percentual comissão')),
                ('dataentrega', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da entrega')),
                ('datacancelamento', models.DateTimeField(null=True, verbose_name='Data de cancelamento')),
                ('observacao', models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Observação')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('vendedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
            },
        ),
        migrations.CreateModel(
            name='ItensPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Quantidade')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Preço')),
                ('desconto_perc', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Percentual de desconto')),
                ('detalhamento', models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Detalhes/Obs')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoVenda', to='core.pedidovenda')),
                ('prduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoVenda', to='core.produto')),
            ],
            options={
                'verbose_name': 'Item de Pedido de Venda',
                'verbose_name_plural': 'Itens de Pedido de Venda',
            },
        ),
    ]
